### ISSUE TITLE
Device port is not showing on Android chrome app

### ISSUE THREAD

**Issue by rohitdharavath** [GoogleChromeLabs/serial-terminal#17]
I am trying to connect to an external device to get data on mobile web page using chrome **navigator.serial.requestPort()**.
It was working on desktop chrome app but not working on mobile. Even checked in serial-terminal. But no ports are displayed.

**Comment by reillyeon** [comment]
Chrome only supports the Serial API on desktop platforms because Android doesn't have a serial API. Resolving #1 will fix this for USB serial devices and Bluetooth Low Energy devices once those are also supported by the library. Chromium [issue 1043300](https://bugs.chromium.org/p/chromium/issues/detail?id=1043300) will resolve this for Bluetooth Classic devices.
