### ISSUE TITLE
Chrome on Android with CP2104

### ISSUE THREAD

**Issue by lichard49** [GoogleChromeLabs/serial-terminal#42]
Hi!

I am using an ESP32-Wrover which uses the CP2104 for USB to UART.  I can use this serial terminal app to interface with it on desktop, but not on Android (via Chrome).  I did include the [polyfill](https://github.com/GoogleChromeLabs/serial-terminal/pull/25) parameter, so the device choosing dialog does appear.  However, it still reports "no compatible devices".  I'm curious if this is expected -- my understanding of the polyfill is that it should work with anything WebUSB is able to detect, and going to `about://device-log` does list events for plugging in/out, even recognizing the chip name correctly.

Thanks in advance!

Richard

**Comment by reillyeon** [comment]
The CP2104 implements a non-standard USB to serial interface and so isn't supported currently by the polyfill. https://github.com/google/web-serial-polyfill/issues/9 is the cannonical issue for adding support for this chip to the polyfill library. We don't have any firm plans for implementing this but patches are welcome.

**Comment by lichard49** [comment]
Do you have any pointers on how to get started with adding support myself?

**Comment by reillyeon** [comment]
You'll need to find documentation for the chip's USB interface (commands to set baud rate, etc.) and then modify the polyfill to send those instead of the ones for the standard CDC-ACM interface. It would be similar to the changes made in https://github.com/google/web-serial-polyfill/commit/f360269d38a141b7418f7d093f1e5180fd520053 to support FTDI's custom interface.
