### ISSUE TITLE
Support for SPP on Chrome Android?

### ISSUE THREAD

**Issue by zcattacz** [GoogleChromeLabs/serial-terminal#70]
It's common to have label printers, scanners, card readers, connecred via SPP on industrial mobile devices. None of these generate a lot of data.

Please support access to these serial devices on Chrome Android. Or is there any app that can bridge the interface in there?

This ability may bring attention from developers from those sectors. A lot of E-commerce users are using these devices  at home besides traditional industrial users in shops, factories and warehouses.

**Comment by reillyeon** [comment]
This is tracked in the Chromium project ashttps://issues.chromium.org/issues/40115202 (see the [comment #39](https://issues.chromium.org/issues/40115202#comment39)). Please click the "+1" button on that page to signal your support for supporting this API on Android.

Closing this issue since this is the issue tracker for the specification, not implementations.

**Comment by zcattacz** [comment]
OK, thank you for the response.
